^0::
Send, aa
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, bb
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, cc
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, dd
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, ee
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, ff
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, gg
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, hh
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, ii
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, jj
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, kk
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, ll
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, mm
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, nn
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, oo
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, pp
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, rr
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, ss
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, tt
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, oo
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, uu
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, ww
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, qq
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, vv
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, xx
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, yy
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, zz
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, 11
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, 22
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, 33
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, 44
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, 55
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, 66
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, 77
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, 88
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, 99
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, ..
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
Send, __
sleep, 1200
Send, {BackSpace}
Send, {BackSpace}
return